<?php

// Language definitions used in all admin files
$lang_admin_bans = array(

'Ban advanced'					=>	'Options avancés des bannissements',
'Ban advanced heading'			=>	'Bannir par nom d\'utilisateur avec une IP et le courriel sinon bannir par IP, par courriel ou les deux',
'Ban criteria legend'			=>	'Critère de bannissement',
'Ban settings legend'			=>	'Options de bannissement',
'Ban IP warning'				=>	'<strong>Attention!</strong> Vous devez être prudent lorsque vous bannissez un rang d\'IP car il est possible que plusieurs utilisateurs y correspondent.',
'Current ban head'				=>	'Banni par %s',
'Username'						=>	'Nom d\'utilisateur:',
'Username to ban label'			=>	'Nom d\'utilisateur à bannir',
'Ban creator'					=>	'Auteur du bannissement',
'IP-addresses to ban label'		=>	'Adresses IP à bannir',
'IP-addresses help'				=>	'L\'IP ou le rang IP que vous souhaitez bannir (ex. 150.11.110.1 ou 150.11.110). Séparez les adresses avec des espaces. Si une IP est déjà entré, c\'est qu\'il s\'agit de la dernière IP connue de cet utilisateur dans la base de données.',
'IP-addresses help stats'		=>	'Cliquez sur le lien suivant pour voir les statistiques IP de cet utilisateur: ',
'IP-addresses help link'		=>	'Statistiques IP de cet utilisateur',
'E-mail/domain to ban label'	=>	'Courriel ou domaine à bannir',
'E-mail/domain help'			=>	'Le courriel ou le nom de domaine que vous souhaitez bannir (ex. quelquun@exemple.com ou exemple.com). Voir "Permettre l\'inscription avec des adresses courriel bannies" dans les paramètres d\'inscription pour plus d\'informations.',
'Ban message label'				=>	'Message de bannissement',
'Ban message help'				=>	'Afficher l\'utilisateur banni quand il/elle visite le forum',
'Expire date label'				=>	'Date d\'expiration du bannissement',
'Expire date help'				=>	'Date à laquelle le bannissement sera automatique levé (format: AAAA-MM-JJ). Laissez blanc pour faire une annulation manuelle.',
'Expires'						=>	'Expire:',
'Message'						=>	'Message:',
'New ban heading'				=>	'Bannissement spécifié par nom d\'utilisateur',
'New ban legend'				=>	'Nouveau bannissement',
'Advanced ban info'				=>	'La page suivante va vous permettre d\'entrer une IP personnalisé ou un courriel. Si vous désirez bannir une IP ou un rang d\'IP spécifique ou un courriel, ne remplissez pas cette page.',
'Existing bans heading'			=>	'Éditer ou annuler les bannissement existant',
'Add ban'						=>	'Ajouter un bannissement',
'Save ban'						=>	'Sauvegarder un bannissement',
'E-mail'						=>	'Courriel:',
'IP-ranges'						=>	'IP/Rang IP:',
'Reason'						=>	'Raison',
'No bans'						=>	'Aucun bannisement dans la liste.',
'Edit ban'						=>	'Éditer le bannissement',
'Remove ban'					=>	'Annuler le bannissement',
'Edit or remove'				=>	'%s ou %s',
'Ban removed'					=>	'Bannissement annulé.',
'Ban added'						=>	'Bannissement ajouté.',
'Ban edited'					=>	'Bannissement édité.',
'No user id message'			=>	'Aucun utilisateur avec cet ID n\'est enregistré.',
'No user username message'		=>	'Aucun utilisateur avec ce nom d\'utilisateur n\'est enregistré. Si vous désirez ajouter un bannissement qui n\'est pas lié à un nom d\'utilisateur, n\'indiquez pas de nom d\'utilisateur.',
'User is admin message'			=>	'L\'utilisateur est un administrateur et ne peut être banni. Si vous désirez bannir un administrateur, vous devez d\'abord le changer de groupe.',
'Must enter message'			=>	'Vous devez entrer au moins une des informations suivantes: un nom d\'utilisateur, une adresse IP ou une adresse courriel.',
'Invalid IP message'			=>	'Vous avez entré une IP ou un rang IP invalide.',
'Can\'t ban guest user'			=>	'Les utilisateurs anonyme ne peuvent être banni.',
'Invalid e-mail message'		=>	'L\'adresse courriel (ex. utilisateur@exemple.com) ou le nom de domaine (ex. exemple.com) que vous avez entré est invalide.',
'Invalid expire message'		=>	'Vous avez entré une date d\'expiration invalide. Le format doit être AAAA-MM-JJ et la date doit au moins correspondre à demain.',


);
